#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# move to project directory
cd $DIR


LINK_SRC=$DIR/run
LINK_DEST=/usr/local/bin/dndbuddy

if [ -e $LINK_DEST ]; then
    echo "[-] The link ($LINK_DEST) already exists.  The program may already be installed."
    echo "    To perform a fresh install, remove the existing file with"
    echo "        rm $LINK_DEST"
    echo "    and re-run this install script."
    exit 1
fi

ln -s $LINK_SRC $LINK_DEST
echo "[+] DnDBuddy installed.  Invoke with 'dndbuddy'."
